version: '3.8'

services:
  db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "/wait-for-it.sh db:5432 -- python manage.py migrate &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/home/app/web/logs  # Add this line
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:
