# Generated by Django 4.2.7 on 2024-02-14 18:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('est_duration', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_units', models.IntegerField()),
                ('fungible', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_models',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('unit_size', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateIndex',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rotations', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule_template_index',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'segments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SegmentParam',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('container', models.BooleanField(default=False)),
                ('contained', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('calc_pay', models.IntegerField(default=0)),
                ('calc_available', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'segment_params',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeResourceItems',
            fields=[
                ('resource_item_code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
            ],
            options={
                'db_table': 'time_resource_items',
                'ordering': ['resource_item_code'],
                'unique_together': {('resource_item_code', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='ModalCount',
            fields=[
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='modal_count', serialize=False, to='config.segment')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_quantity', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('logic', models.CharField(default='NOT', max_length=3)),
                ('sub', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('category_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.servicecategory')),
            ],
            options={
                'db_table': 'modal_count',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeResourcesQueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('segment', models.CharField(max_length=50)),
                ('segment_start', models.DateTimeField()),
                ('segment_end', models.DateTimeField()),
                ('date_created', models.DateField()),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('resource_item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
                ('resource_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
                ('segment_params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.segmentparam')),
            ],
            options={
                'db_table': 'time_resources_queue_history',
                'ordering': ['archived_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeResourcesQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start', models.DateTimeField()),
                ('segment_end', models.DateTimeField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
                ('resource_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_resources_queue', to='config.segment')),
                ('segment_params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.segmentparam')),
            ],
            options={
                'db_table': 'time_resources_queue',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeResourceScheduleIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rotation', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
                ('resource_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
                ('schedule_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.scheduletemplateindex')),
            ],
            options={
                'db_table': 'time_resource_schedule_index',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('total_duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.servicecategory')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='config.segmentparam'),
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('wk', models.CharField(max_length=1)),
                ('wkday', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('sched_container', models.DurationField()),
                ('lunch_duration', models.DurationField(blank=True, null=True)),
                ('gross_sched', models.DurationField()),
                ('breaks_duration', models.DurationField(blank=True, null=True)),
                ('net_sched', models.DurationField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('index_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.scheduletemplateindex')),
            ],
            options={
                'db_table': 'schedule_templates',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.resourcetype', to_field='code'),
        ),
        migrations.CreateModel(
            name='ResourceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_start', models.DateTimeField()),
                ('available_end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
                ('resource_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
            ],
            options={
                'db_table': 'resource_availablity',
                'ordering': ['date_created', 'available_start'],
            },
        ),
        migrations.CreateModel(
            name='PhaseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('phase_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.phase')),
                ('resource_models_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
                ('resource_types_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcetype')),
            ],
            options={
                'db_table': 'phase_resources',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModalSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.servicecategory')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.services')),
            ],
            options={
                'db_table': 'modal_select',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='config.timeresourceitems')),
                ('resource_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('naf', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('resource_model', models.CharField(max_length=5)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='config.timeresourceitems')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='modal_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.modalcount'),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('est_duration', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.orders')),
                ('modal_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.modalcount')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='modalcount',
            name='service_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.services'),
        ),
    ]
