# Generated by Django 5.0.3 on 2024-03-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resource_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employees', serialize=False, to='config.timeresourceitems'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='resource_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipment', serialize=False, to='config.timeresourceitems'),
        ),
    ]
