# Generated by Django 5.0.3 on 2024-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_employee_resource_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='leejhwalker@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
