# Generated by Django 5.0.2 on 2024-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_modalcount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalselect',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
