# Generated by Django 4.2.6 on 2023-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_servicecategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('total_duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
