# Generated by Django 5.0.2 on 2024-02-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_modalselect_code_alter_servicecategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_resources_queue', to='config.segment'),
        ),
    ]
