# Generated by Django 4.2.6 on 2023-10-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_services_alter_servicecategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='sercat_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.servicecategory'),
            preserve_default=False,
        ),
    ]
