# Generated by Django 5.0.3 on 2024-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmployeeParams',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Employee Parameter',
                'verbose_name_plural': 'Admin Employee Parameters',
                'db_table': 'admin_employee_params',
                'ordering': ['code'],
            },
        ),
    ]
