# Generated by Django 4.2.6 on 2023-10-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_services_sercat_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='sercat_code',
            new_name='service_category_id',
        ),
    ]
