# Generated by Django 5.0.3 on 2024-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_adminemployeeparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemployeeparams',
            name='location_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminemployeeparams',
            name='team_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
