# Generated by Django 5.0.2 on 2024-02-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_timeresourcesqueue_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='resource_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
        ),
    ]
