# Generated by Django 4.2.6 on 2023-10-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_rename_sercat_code_services_service_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_category_id',
            new_name='service_category',
        ),
    ]
