# Generated by Django 5.0.3 on 2024-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_adminemployeeparams_location_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='staff_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
