# Generated by Django 4.2.6 on 2023-11-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_rename_service_category_id_services_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_category',
        ),
    ]
