# Generated by Django 5.0.2 on 2024-02-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_timeresourcesqueue_resource_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceavailability',
            name='resource_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
        ),
    ]
