# Generated by Django 5.0.3 on 2024-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_timeresourcesqueuehistory_staff_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueuehistory',
            name='staff_timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
