# Generated by Django 4.2.6 on 2023-11-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_remove_services_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_category',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
