# Generated by Django 5.0.3 on 2024-03-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_timeresourcesqueuehistory_staff_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'franchise',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.RemoveField(
            model_name='adminemployeeparams',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='adminemployeeparams',
            name='team_code',
        ),
        migrations.AddField(
            model_name='adminemployeeparams',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminemployeeparams',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.location'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='adminemployeeparams',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.role'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmployeeCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.franchise')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.team')),
            ],
            options={
                'verbose_name_plural': 'Employee Coordinates',
                'db_table': 'employee_coordinates',
            },
        ),
        migrations.AddField(
            model_name='adminemployeeparams',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.team'),
            preserve_default=False,
        ),
    ]
