# Generated by Django 4.2.6 on 2023-11-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_services_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_category',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
