# Generated by Django 5.0.2 on 2024-02-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_resourceavailability_resource_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceavailability',
            name='resource_item',
            field=models.ForeignKey(default='dpmontoya', on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='resource_item_code',
            field=models.ForeignKey(default='dpmontoya', on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='resource_model',
            field=models.ForeignKey(default='BARB', on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='segment',
            field=models.ForeignKey(default='CNTN', on_delete=django.db.models.deletion.CASCADE, related_name='time_resources_queue', to='config.segment'),
            preserve_default=False,
        ),
    ]
