# Generated by Django 4.2.6 on 2023-11-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_alter_services_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.servicecategory'),
        ),
    ]
