# Generated by Django 5.0.3 on 2024-03-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_franchise_location_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecoordinates',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.employee'),
        ),
        migrations.AlterField(
            model_name='adminemployeeparams',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.employee'),
        ),
        migrations.AddField(
            model_name='employeecoordinates',
            name='role',
            field=models.ForeignKey(default='BARB', on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
