# Generated by Django 5.0.2 on 2024-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_simplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplemodel',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
