# Generated by Django 4.2.6 on 2023-11-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_alter_services_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.servicecategory')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.services')),
            ],
            options={
                'db_table': 'modal_select',
            },
        ),
        migrations.CreateModel(
            name='ModalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_quantity', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.servicecategory')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.services')),
            ],
            options={
                'db_table': 'modal_count',
            },
        ),
    ]
