# Generated by Django 4.2.6 on 2023-11-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_modalselect_modalcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalcount',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modalselect',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
