# Generated by Django 5.0.2 on 2024-02-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_alter_simplemodel_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleModel',
        ),
    ]
