# Generated by Django 4.2.6 on 2023-11-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_modalcount_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalcount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='modalselect',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id']},
        ),
    ]
