# Generated by Django 5.0.2 on 2024-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_delete_simplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'simple_model',
                'ordering': ['code'],
            },
        ),
    ]
