# Generated by Django 5.0.2 on 2024-02-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_simplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleModel',
        ),
    ]
