# Generated by Django 4.2.7 on 2023-11-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_alter_modalcount_options_alter_modalselect_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalcount',
            name='logic',
            field=models.CharField(default='NOT', max_length=3),
        ),
    ]
