# Generated by Django 4.2.7 on 2023-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_modalcount_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalcount',
            name='sub',
            field=models.IntegerField(default=0),
        ),
    ]
