# Generated by Django 5.0.2 on 2024-02-19 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_delete_simplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='segment_params',
            field=models.ForeignKey(default='PP', on_delete=django.db.models.deletion.PROTECT, to='config.segmentparam'),
            preserve_default=False,
        ),
    ]
