# Generated by Django 5.0.2 on 2024-02-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_alter_timeresourcesqueue_segment_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.orders', to_field='order_number'),
        ),
        migrations.AddField(
            model_name='timeresourcesqueuehistory',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.orders', to_field='order_number'),
        ),
    ]
