# Generated by Django 4.2.7 on 2023-11-30 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_modalcount_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_start', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('est_duration', models.IntegerField(blank=True, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelTable(
            name='modalcount',
            table='ModalCount',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_start', models.TimeField(blank=True, null=True)),
                ('est_duration', models.IntegerField(blank=True, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('modal_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.modalcount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.orders')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
    ]
