# Generated by Django 5.0.2 on 2024-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_timeresourcesqueue_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='staff_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='staff_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeresourcesqueuehistory',
            name='staff_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeresourcesqueuehistory',
            name='staff_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
