# Generated by Django 4.2.7 on 2023-11-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_orders_alter_modalcount_table_orderitems'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modalcount',
            table='modal_count',
        ),
    ]
