# Generated by Django 4.2.7 on 2024-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_alter_modalcount_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='est_start',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
