# Generated by Django 5.0.2 on 2024-03-04 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_alter_modalcount_code_alter_phaseresource_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleElements',
            fields=[
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='schedule_elements', serialize=False, to='config.segment')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule_elements',
                'ordering': ['code'],
            },
        ),
    ]
