# Generated by Django 4.2.7 on 2024-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_alter_orderitems_est_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
