# Generated by Django 5.0.2 on 2024-03-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_scheduleelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='segment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
