# Generated by Django 4.2.7 on 2024-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_orderitems_order_number_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
