# Generated by Django 5.0.2 on 2024-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_timeresourcesqueue_segment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueuehistory',
            name='segment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
