# Generated by Django 5.0.2 on 2024-03-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_timeresourcesqueuehistory_segment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='segment_name',
            field=models.CharField(default='fake name', max_length=100),
            preserve_default=False,
        ),
    ]
