# Generated by Django 5.0.2 on 2024-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_alter_timeresourcesqueue_segment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='staff_timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
