# Generated by Django 4.2.7 on 2024-01-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_alter_employee_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('unit_size', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type_code', models.CharField(max_length=5)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_units', models.IntegerField()),
                ('fungible', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.resourcetype', to_field='code')),
            ],
            options={
                'db_table': 'resource_models',
                'ordering': ['id'],
            },
        ),
    ]
