# Generated by Django 5.0.2 on 2024-03-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_employeephases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeephases',
            name='phase_resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_phases', to='config.phaseresource'),
        ),
    ]
