# Generated by Django 4.2.7 on 2024-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_phase_phaseresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeResourcesQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_item_code', models.CharField(max_length=5)),
                ('resource_item_name', models.CharField(max_length=100)),
                ('segment_type', models.IntegerField()),
                ('segment', models.CharField(max_length=50)),
                ('segment_start', models.TimeField()),
                ('segment_end', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'time_resources_queue',
            },
        ),
    ]
