# Generated by Django 5.0.3 on 2024-03-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_alter_employeephases_phase_resource_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'Service Categories'},
        ),
    ]
