# Generated by Django 4.2.7 on 2024-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_timeresourcesqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
