# Generated by Django 5.0.3 on 2024-03-09 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_alter_orderitems_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeephases',
            name='resource_item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_phases', to='config.employee'),
        ),
    ]
