# Generated by Django 4.2.7 on 2024-01-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_alter_timeresourcesqueue_resource_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseresource',
            name='resource_types_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.resourcetype'),
        ),
        migrations.AlterField(
            model_name='modalcount',
            name='category_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.servicecategory'),
        ),
        migrations.AlterField(
            model_name='modalcount',
            name='service_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.services'),
        ),
        migrations.AlterField(
            model_name='modalselect',
            name='category_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.servicecategory'),
        ),
        migrations.AlterField(
            model_name='modalselect',
            name='service_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.services'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='modal_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.modalcount'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.orders'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.modalcount'),
        ),
        migrations.AlterField(
            model_name='phaseresource',
            name='phase_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.phase'),
        ),
        migrations.AlterField(
            model_name='phaseresource',
            name='resource_models_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.resourcemodel'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.servicecategory'),
        ),
    ]
