# Generated by Django 4.2.7 on 2024-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_phaseresource_resource_types_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalcount',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
