# Generated by Django 4.2.7 on 2024-01-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='resource_model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.resourcemodel'),
        ),
    ]
