# Generated by Django 4.2.7 on 2024-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_timeresourcesqueue_resource_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentParam',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('container', models.BooleanField(default=False)),
                ('contained', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('calc_pay', models.IntegerField(default=0)),
                ('calc_available', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'segment_params',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='timeresourcesqueue',
            options={'ordering': ['id']},
        ),
    ]
