# Generated by Django 4.2.7 on 2024-01-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_timeresourcesqueue_segment_params_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeresourcesqueue',
            old_name='resource_model_id',
            new_name='resource_model',
        ),
        migrations.RenameField(
            model_name='timeresourcesqueue',
            old_name='segment_params_id',
            new_name='segment_params',
        ),
    ]
