# Generated by Django 4.2.7 on 2024-01-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0035_rename_resource_model_id_timeresourcesqueue_resource_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_start', models.DateTimeField()),
                ('available_end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.timeresourcesqueue')),
            ],
            options={
                'db_table': 'resource_availablity',
                'ordering': ['date_created', 'available_start'],
            },
        ),
    ]
