# Generated by Django 4.2.7 on 2024-01-28 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_alter_resourceavailability_resource_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplateIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule_template_index',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('wk', models.CharField(max_length=1)),
                ('wkday', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('sched_container', models.DurationField()),
                ('lunch_duration', models.DurationField(blank=True, null=True)),
                ('gross_sched', models.DurationField()),
                ('breaks_duration', models.DurationField(blank=True, null=True)),
                ('net_sched', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('index_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.scheduletemplateindex')),
            ],
            options={
                'db_table': 'schedule_templates',
                'ordering': ['code'],
            },
        ),
    ]
