# Generated by Django 4.2.7 on 2024-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_scheduletemplateindex_scheduletemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scheduletemplateindex',
            name='id',
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduletemplateindex',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
