# Generated by Django 4.2.7 on 2024-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_remove_scheduletemplate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplate',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scheduletemplateindex',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
