# Generated by Django 4.2.7 on 2024-01-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_alter_scheduletemplate_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='index_code',
        ),
    ]
