# Generated by Django 4.2.7 on 2024-01-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_scheduletemplate_index_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScheduleIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rotation', models.CharField(blank=True, max_length=1, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.employee')),
                ('schedule_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.scheduletemplateindex')),
            ],
            options={
                'db_table': 'employee_schedule_index',
            },
        ),
    ]
