# Generated by Django 4.2.7 on 2024-01-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0044_employeescheduleindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeescheduleindex',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeescheduleindex',
            name='first_rotation',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
