# Generated by Django 4.2.7 on 2024-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0045_alter_employeescheduleindex_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employeescheduleindex',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
