# Generated by Django 4.2.7 on 2024-01-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0046_alter_employee_options_remove_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescheduleindex',
            name='employee',
            field=models.ForeignKey(default='dpmontoya', on_delete=django.db.models.deletion.CASCADE, to='config.employee'),
            preserve_default=False,
        ),
    ]
