# Generated by Django 4.2.7 on 2024-01-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_employeescheduleindex_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeresourcesqueue',
            name='resource_item_name',
        ),
    ]
