# Generated by Django 4.2.7 on 2024-01-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0048_remove_timeresourcesqueue_resource_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescheduleindex',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
    ]
