# Generated by Django 4.2.7 on 2024-01-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0050_alter_resourcemodel_options_remove_resourcemodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeescheduleindex',
            name='resource_model',
        ),
        migrations.RemoveField(
            model_name='phaseresource',
            name='resource_models_code',
        ),
        migrations.RemoveField(
            model_name='timeresourcesqueue',
            name='resource_model',
        ),
    ]
