# Generated by Django 4.2.7 on 2024-01-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0051_remove_employeescheduleindex_resource_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescheduleindex',
            name='resource_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.resourcemodel'),
        ),
        migrations.AddField(
            model_name='phaseresource',
            name='resource_models_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.resourcemodel'),
        ),
        migrations.AddField(
            model_name='timeresourcesqueue',
            name='resource_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.resourcemodel'),
        ),
    ]
