# Generated by Django 4.2.7 on 2024-01-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0052_employeescheduleindex_resource_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeresourcesqueue',
            name='segment_type',
        ),
    ]
