# Generated by Django 4.2.7 on 2024-01-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0053_remove_timeresourcesqueue_segment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcemodel',
            name='type_code',
        ),
    ]
