# Generated by Django 4.2.7 on 2024-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0055_timeresourcesqueuehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourcesqueuehistory',
            name='original_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
