# Generated by Django 4.2.7 on 2024-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0056_timeresourcesqueuehistory_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplateindex',
            name='rotations',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
