# Generated by Django 4.2.7 on 2024-02-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0058_alter_resourceavailability_resource_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resource_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.resourcemodel')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['code'],
            },
        ),
    ]
