# Generated by Django 4.2.7 on 2024-02-01 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0059_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeResourceItems',
            fields=[
                ('resource_item_code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.resourcemodel')),
            ],
            options={
                'db_table': 'time_resource_items',
                'ordering': ['resource_item_code'],
            },
        ),
        migrations.CreateModel(
            name='TimeResourceScheduleIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rotation', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems')),
                ('resource_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.resourcemodel')),
                ('schedule_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.scheduletemplateindex')),
            ],
            options={
                'db_table': 'time_resource_schedule_index',
            },
        ),
         ]
