# Generated by Django 4.2.7 on 2024-02-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_timeresourceitems_timeresourcescheduleindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcescheduleindex',
            name='resource_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.employee'),
        ),
        migrations.DeleteModel(
            name='EmployeeScheduleIndex',
        ),
    ]
