# Generated by Django 4.2.7 on 2024-02-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0061_alter_timeresourcescheduleindex_resource_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='resource_model',
        ),
    ]
