# Generated by Django 4.2.7 on 2024-02-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_alter_employee_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeresourceitems',
            old_name='purchase_date',
            new_name='start_date',
        ),
    ]
