# Generated by Django 4.2.7 on 2024-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0064_rename_purchase_date_timeresourceitems_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeresourceitems',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
