# Generated by Django 4.2.7 on 2024-02-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0066_rename_purchase_date_equipment_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeresourceitems',
            unique_together={('resource_item_code', 'start_date', 'end_date')},
        ),
    ]
