# Generated by Django 4.2.7 on 2024-02-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0067_alter_timeresourceitems_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='time_resource_item',
            field=models.ForeignKey(default='dmontoya', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='config.timeresourceitems'),
            preserve_default=False,
        ),
    ]
