# Generated by Django 4.2.7 on 2024-02-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0069_remove_employee_time_resource_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='resource_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='config.timeresourceitems'),
        ),
        migrations.AlterField(
            model_name='resourceavailability',
            name='resource_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
        ),
        migrations.AlterField(
            model_name='timeresourcescheduleindex',
            name='resource_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
        ),
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='resource_item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
        ),
        migrations.AlterField(
            model_name='timeresourcesqueuehistory',
            name='resource_item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.timeresourceitems'),
        ),
    ]
