# Generated by Django 4.2.7 on 2024-02-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0079_alter_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resource_model',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phaseresource',
            name='resource_models_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phaseresource',
            name='resource_types_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourceavailability',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourceitems',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourcescheduleindex',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeresourcesqueuehistory',
            name='resource_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.resourcemodel'),
            preserve_default=False,
        ),
    ]
