# Generated by Django 4.2.7 on 2024-02-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0080_alter_employee_resource_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='modal_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.modalcount'),
            preserve_default=False,
        ),
    ]
