# Generated by Django 4.2.7 on 2024-02-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0081_alter_orderitems_modal_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('segment_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='config.segmentparam')),
            ],
            options={
                'db_table': 'segments',
                'ordering': ['code'],
            },
        ),
    ]
