# Generated by Django 4.2.7 on 2024-02-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0082_segment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalcount',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='modalcount',
            name='id',
        ),
        migrations.AlterField(
            model_name='modalcount',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='modal_count', serialize=False, to='config.segment'),
        ),
    ]
