# Generated by Django 4.2.7 on 2024-02-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0083_alter_modalcount_options_remove_modalcount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeresourcesqueue',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_resources_queue', to='config.segment'),
        ),
    ]
